id: P22A027A3
initial_creation_type: input
source_metadata:
  title: Dhammapada
  language: zh
  volumes:
    114f576fae66418aab120ea8cee11487:
      title: 'CIII_Chapter 21: Pakiṇṇavaggo'
      base_file: 'CIII_Chapter 21: Pakiṇṇavaggo.txt'
      work_id: WAF0DDAFD
    e847c2a0de214f5ebcff8ae801a54f5e:
      title: 'CIII_Chapter 22: Nirayavaggo'
      base_file: 'CIII_Chapter 22: Nirayavaggo.txt'
      work_id: W8345492E
    1140f3a3e4214de3820f654ee55eeceb:
      title: 'CIII_Chapter 23: Nāgavaggo'
      base_file: 'CIII_Chapter 23: Nāgavaggo.txt'
      work_id: W2DD6F9FD
    6751836c4da5499884e3d5e1d68cc333:
      title: 'CIII_Chapter 24: Taṇhāvaggo'
      base_file: 'CIII_Chapter 24: Taṇhāvaggo.txt'
      work_id: WE2344537
    1b600e87a2ab4c69a805239a7cdf73c8:
      title: 'CIII_Chapter 25: Bhikkhuvaggo'
      base_file: 'CIII_Chapter 25: Bhikkhuvaggo.txt'
      work_id: W555BCE4E
    47073f387fbf47f09cca139267350236:
      title: 'CIII_Chapter 26: Brāhmaṇavaggo'
      base_file: 'CIII_Chapter 26: Brāhmaṇavaggo.txt'
      work_id: WC558B909
    160206c1b5cc475a9e7fac23f0488f78:
      title: 'CII_Chapter 11: Jarāvaggo'
      base_file: 'CII_Chapter 11: Jarāvaggo.txt'
      work_id: WE3979FE9
    a8b53b516864404190ebeb1a53ca2234:
      title: 'CII_Chapter 12: Attavaggo'
      base_file: 'CII_Chapter 12: Attavaggo.txt'
      work_id: WDAB1812A
    6908860b0a864f0cbe6dd50c308818fa:
      title: 'CII_Chapter 13: Lokavaggo'
      base_file: 'CII_Chapter 13: Lokavaggo.txt'
      work_id: W79C88D9A
    a7750d9f3fd04b9ea78f8854827c432d:
      title: 'CII_Chapter 14: Buddhavaggo'
      base_file: 'CII_Chapter 14: Buddhavaggo.txt'
      work_id: W53CF8FA5
    cb15b99152254a32a2249bc3967a525e:
      title: 'CII_Chapter 15: Sukhavaggo'
      base_file: 'CII_Chapter 15: Sukhavaggo.txt'
      work_id: WAAA38446
    1a2244eb07dc49bdab6d3e7332e888bf:
      title: 'CII_Chapter 16: Piyavaggo'
      base_file: 'CII_Chapter 16: Piyavaggo.txt'
      work_id: WB2440CCC
    e08f054596c140debacf2bae3e74bb56:
      title: 'CII_Chapter 17: Kodhavaggo'
      base_file: 'CII_Chapter 17: Kodhavaggo.txt'
      work_id: W8EDE8808
    f2b9548ea209459490b2762535f1d72a:
      title: 'CII_Chapter 18: Malavaggo'
      base_file: 'CII_Chapter 18: Malavaggo.txt'
      work_id: W42E2C402
    7a179c4573ea4763b27beb0809df4ab4:
      title: 'CII_Chapter 19: Dhammaṭṭhavaggo'
      base_file: 'CII_Chapter 19: Dhammaṭṭhavaggo.txt'
      work_id: W84E903B8
    6371e8fff01541d69dcf134a1bd1c80f:
      title: 'CII_Chapter 20: Maggavaggo'
      base_file: 'CII_Chapter 20: Maggavaggo.txt'
      work_id: W4ABD228D
    b226630211db46ecb46d46cd94c13bed:
      title: CIV_Additional Chinese verses
      base_file: CIV_Additional Chinese verses.txt
      work_id: W1871C0BC
    d5a2fd6dcb804c44aa5b45fa21e4cd35:
      title: CIV_Additional Gāndhārī verses
      base_file: CIV_Additional Gāndhārī verses.txt
      work_id: W08D02D21
    504e610f68aa4da8b1a89d71eaadf2e1:
      title: CIV_Additional Prakrit verses
      base_file: CIV_Additional Prakrit verses.txt
      work_id: W110350D3
    458cd038247348428e3ceb7254504182:
      title: 'CI_Chapter 10: Daṇaḍavaggo'
      base_file: 'CI_Chapter 10: Daṇaḍavaggo.txt'
      work_id: W968F16F6
    9c4ac1223964452aa0afec6a39d35198:
      title: 'CI_Chapter 1: Yamakavaggo'
      base_file: 'CI_Chapter 1: Yamakavaggo.txt'
      work_id: W6AF62446
    4d1becf4e9ad48199f9c8ed5292005b8:
      title: 'CI_Chapter 2: Appamādavaggo'
      base_file: 'CI_Chapter 2: Appamādavaggo.txt'
      work_id: W7B448ADD
    b809964be04047a29e607cae4348d478:
      title: 'CI_Chapter 3: Cittavaggo'
      base_file: 'CI_Chapter 3: Cittavaggo.txt'
      work_id: WB491F3F9
    b9f65bf711474165bc07deedb16aad0d:
      title: 'CI_Chapter 4: Pupphavaggo'
      base_file: 'CI_Chapter 4: Pupphavaggo.txt'
      work_id: WEEFE11D4
    d3aba4bf9f2f4a0cb106f6544b6c006c:
      title: 'CI_Chapter 5: Bālavaggo'
      base_file: 'CI_Chapter 5: Bālavaggo.txt'
      work_id: W80333D23
    1f1969bd39df4f1fa0dc713dad8582e3:
      title: 'CI_Chapter 6: Paṇḍitavaggo'
      base_file: 'CI_Chapter 6: Paṇḍitavaggo.txt'
      work_id: W546C38CA
    598b29f77c4e41b4b2fa32488f9f8df5:
      title: 'CI_Chapter 7: Arahantavaggo'
      base_file: 'CI_Chapter 7: Arahantavaggo.txt'
      work_id: W841F0D84
    bab719384a3f478c9071d7bcf5f73dfb:
      title: 'CI_Chapter 8: Sahassavaggo'
      base_file: 'CI_Chapter 8: Sahassavaggo.txt'
      work_id: W2F21B15A
    5370950e13e74fd1b8f69d6fb648daed:
      title: 'CI_Chapter 9: Pāpavaggo'
      base_file: 'CI_Chapter 9: Pāpavaggo.txt'
      work_id: W4BC4B557
    8d992198264643079cdedf83c7c37415:
      title: Colophon
      base_file: Colophon.txt
      work_id: WFF6CF4AD
    104b7a99b08749b78e5700bfa22b0b3e:
      title: Preface
      base_file: Preface.txt
      work_id: W8E70A707
    34a021a1cfca486c9666799caab30002:
      title: Title
      base_file: Title.txt
      work_id: W5C142A9B
  chapter_to_tile:
    CI: Chapters 1-10
    CII: Chapters 11-20
    CIII: Chapters 21-26
    CIV: Additional verses not in the Pāli edition
created_at: '2022-03-01T23:17:03.233409'
last_modified_at: '2022-03-01T23:17:03.233416'
